# Generated by Django 5.1.2 on 2024-10-27 06:24

import ckeditor_uploader.fields
import django_jsonform.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('banner', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=150)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('num_of_likes', models.IntegerField(default=0)),
                ('tags', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
            ],
        ),
    ]
